### ISSUE TITLE
Is there any way we can use `secp256k1` instead?

### ISSUE THREAD

**Issue by cryptoquick** [ecies/rs#112]
The reason I ask is because we already include the [secp256k1](https://docs.rs/secp256k1/latest/secp256k1/) crate in our WASM binary for BDK, so having multiple implementations for the same thing is suboptimal. Also, [according to my tests](https://github.com/cryptoquick/rana/tree/perf-k256), the k256 library is substantially slower than the C library, though I'm not sure if this problem is similar for libsecp256k1, and I'm also not sure how many times public keys need to be computed during encryption and decryption.

**Comment by kigawas** [comment]
secp256k1 is C and libsecp256k1 is Rust. If there are no specific reasons I'd rather recommend the pure Rust libsecp256k1.

They are both using a "context" technique (you can think it as creating a big table of 1M bytes on static or on heap) to speed up scalar multiplication (basically this happens on key exchange) on curve. I have not checked thoroughly, but the diffrence should be trivial since they are the same trade-off for speed.

**Comment by cryptoquick** [comment]
Well, the major problem with mixing different implementations is that the types don't match, so things have to be serialized into bytes in order to interoperate. This can result in errors like the one described in this issue: https://github.com/rust-bitcoin/rust-secp256k1/issues/584

The other problem is, we're including multiple implementations in [bitmask-core](https://github.com/diba-io/bitmask-core), which makes the binary larger, and if we're allocating multiple 1M tables on the heap to accomplish the same task, that's also not ideal.

There's really no benefit for using a pure Rust implementation so far as I'm aware.

**Comment by kigawas** [comment]
I see. It seems you have integrated the Rust binding for C before so you'd like to avoid importing another secp256k1 library again. 

I prefer pure Rust because it's easier to support no_std or WASM and I actually only need the linear multiplication.

If you don't want redundant secp256k1 libraries, you can still implement the ecies function easily like [this](https://github.com/kigawas/Astar/blob/ecies-ext/chain-extensions/ecies/src/utils.rs)

**Comment by cryptoquick** [comment]
Nice, seems straightforward enough! Thank you.
